// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/product/:id": {
    params: {
      "id": string;
    };
  };
  "/app/additional": {
    params: {};
  };
  "/app/checkout": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/orders": {
    params: {};
  };
  "/app/store": {
    params: {};
  };
  "/app/cart": {
    params: {};
  };
  "/app/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/auth/*" | "/app" | "/app/product/:id" | "/app/additional" | "/app/checkout" | "/app/products" | "/app/orders" | "/app/store" | "/app/cart" | "/app/home";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/product/:id" | "/app/additional" | "/app/checkout" | "/app/products" | "/app/orders" | "/app/store" | "/app/cart" | "/app/home";
  };
  "routes/app.product.$id.jsx": {
    id: "routes/app.product.$id";
    page: "/app/product/:id";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.checkout.jsx": {
    id: "routes/app.checkout";
    page: "/app/checkout";
  };
  "routes/app.products.jsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app.orders.jsx": {
    id: "routes/app.orders";
    page: "/app/orders";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.store.jsx": {
    id: "routes/app.store";
    page: "/app/store";
  };
  "routes/app.cart.jsx": {
    id: "routes/app.cart";
    page: "/app/cart";
  };
  "routes/app.home.jsx": {
    id: "routes/app.home";
    page: "/app/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.product.$id": typeof import("./app/routes/app.product.$id.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.checkout": typeof import("./app/routes/app.checkout.jsx");
  "routes/app.products": typeof import("./app/routes/app.products.jsx");
  "routes/app.orders": typeof import("./app/routes/app.orders.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.store": typeof import("./app/routes/app.store.jsx");
  "routes/app.cart": typeof import("./app/routes/app.cart.jsx");
  "routes/app.home": typeof import("./app/routes/app.home.jsx");
};